version: '3'
services:
  frontend:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/my-page:7
    container_name: frontend
    hostname: frontend
    restart: always
    volumes:
      - /apps/lego/certificates:/certs
    ports:
      - 80:80
      - 443:443
