version: '3'
services:
  frontend:
    build: ./frontend
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/my-page:9
    container_name: frontend
    hostname: frontend
    restart: always
    volumes:
      - /apps/lego/certificates:/certs
      - /apps/frontend:/frontend
    ports:
      - 80:80
      - 443:443

  consul-server:
    image: consul:1.0.6
    container_name: consul-server
    hostname: consul-server
    volumes:
      - /apps/consul/server:/consul/data
    command:
      - agent
      - -server
      - -ui
      - -bootstrap-expect=1
      - -client=0.0.0.0

  twitch2telegram:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/twitch2telegram:9c7f4c0
    container_name: twitch2telegram
    hostname: twitch2telegram
    env_file:
      - env/twitch2telegram.env

  rabbitmq:
    image: rabbitmq:3.7.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  sender-telegram:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/sender-telegram:1
    container_name: sender-telegram
    hostname: sender-telegram
    env_file:
      - env/sender-telegram.env

  source-youtube:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/source-youtube:1
    container_name: source-youtube
    hostname: source-youtube
    env_file:
      - env/source-youtube.env
