version: '3'
services:
  frontend:
    build: ./frontend
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/my-page:9
    container_name: frontend
    hostname: frontend
    restart: always
    volumes:
      - /apps/lego/certificates:/certs
      - /apps/frontend:/frontend
    ports:
      - 80:80
      - 443:443

  snsonfirm:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/snsconfirm:latest
    container_name: snsconfirm
    hostname: snsconfirm

  srctwitch:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/srctwitch:59064fa816d7dc42af6d47b33fbdd2246f1b6889
    container_name: srctwitch
    hostname: srctwitch
    env_file:
      - env/srctwitch.env

  srcyoutube:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/srcyoutube:97fe981c172f6ac3c5cb8a9ad6b2834781055f42
    container_name: srcyoutube
    hostname: srcyoutube
    env_file:
      - env/srcyoutube.env

  sendertelegram:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/sendertelegram:e32db965339f35fc4b1b8ff41aa7b300f306412e
    container_name: sendertelegram
    hostname: sendertelegram
    env_file:
      - env/sendertelegram.env

  feed:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/feed:58f7c47b67f32321d51dccb27be188e4722425ba
    container_name: feed
    hostname: feed
    env_file:
      - env/feed.env
    volumes:
      - /apps/feed:/store

  feed-web:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/feed-web:29a82569898948134b28ac6796203508a835c465
    container_name: feed-web
    hostname: feed-web

  diffcalculator:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/diffcalculator:ae8a67968856348dd33dee1c53c2c0e3f3ce2d94
    container_name: diffcalculator
    hostname: diffcalculator
    env_file:
      - env/diffcalculator.env
    volumes:
      - /apps/diff-calculator:/store

  sourcerss:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/sourcerss:63d69cdf9114f17f87a1cc035cc2d1c56b762f76
    container_name: sourcerss
    hostname: sourcerss
    env_file:
      - env/sourcerss.env
