version: '3'
services:
  frontend:
    build: ./frontend
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/my-page:9
    container_name: frontend
    hostname: frontend
    restart: always
    volumes:
      - /apps/lego/certificates:/certs
      - /apps/frontend:/frontend
    ports:
      - 80:80
      - 443:443

  consul-server:
    image: consul:1.0.6
    container_name: consul-server
    hostname: consul-server
    volumes:
      - /apps/consul/server:/consul/data
    command:
      - agent
      - -server
      - -ui
      - -bootstrap-expect=1
      - -client=0.0.0.0

  lego:
    build: ./lego
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/lego:7
    volumes:
      - /apps/lego:/lego
    entrypoint: 
      - tail 
      - -f 
      - /dev/null
    container_name: lego
    hostname: lego

  twitch2telegram:
    image: 563473344515.dkr.ecr.eu-central-1.amazonaws.com/twitch2telegram:1
    container_name: twitch2telegram
    hostname: twitch2telegram
    env_file:
      - .env
